### ISSUE TITLE
change iso8601 to second 

### ISSUE THREAD

**Issue by Yuan-Yu** [RubyStarts3/YPBT-api#26]

**Comment by SOA-KunLin** [comment]
thank for your response.,  please~

**Comment by SOA-KunLin** [comment]
note: clean value object

**Comment by SOA-KunLin** [comment]
reminding: clean lib/*_record.rb

**Comment by SOA-KunLin** [comment]
reminding: timetag_info_repr  timetag_info_reprB  => timetag_mingle_repr timetag_general_repr  timetag_detail_repr

**Comment by SOA-KunLin** [comment]
reminding: comment_info_repr => comment_mingle_repr

**Comment by SOA-KunLin** [comment]
change iso8601 to second => finish

**Comment by SOA-KunLin** [comment]
all issues solved, closed.
